# Generated by Django 3.1.4 on 2020-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='il10',
            options={'managed': True},
        ),
    ]
