# Generated by Django 3.1.4 on 2020-12-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_auto_20201209_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='il10',
            options={'managed': False},
        ),
    ]
